<?php

use Laminas\View\View;

/**
 * @var $this View
 */
?>
<h1>Incluir Imovel</h1>
<form method="post" action="<?= $this->url('cadastros', [
                                'controller' => 'imovel',
                                'action' => 'gravar'
                            ]) ?>">
    Nome: <input type="text" name="nome" autofocus="autofocus" value="<?= $this->imovel->nome ?>">
    <input type="hidden" name="matricula" value="<?= $this->imovel->matricula ?>">
    <input type="submit" value="gravar">
</form>
<p>
    <a href="<?= $this->url('cadastros', [
                    'controller' => 'imovel'
                ]) ?>">Voltar</a>