<?php

/**
 * @var $this Laminas\View\Renderer\PhpRenderer
 */
?>

<h1>Cadastro de Imóveis</h1>
<p><a href="<?= $this->url('cadastros', [
                'controller' => 'imovel',
                'action' => 'editar'
            ]) ?>">Novo imovel</a></p>
<table>
    <thead>
        <tr>
            <th>Matricula</th>
            <th>Nome</th>
        </tr>
    </thead>
    <tbody>
        <?= $this->partialLoop('imoveis.phtml', $this->imoveis) ?>
    </tbody>
</table>
<p>
    <a href="<?= $this->url('cadastros') ?>">Voltar</a>
