<?php
use Laminas\View\View;

/**
 * @var $this View
 */
?>
<h1>Incluir Corretor</h1>
<form method="post" action="<?=$this->url('cadastros',[
'controller' => 'corretor',
'action' => 'gravar'    
])?>">
Nome: <input type="text" name="nome" autofocus="autofocus" value="<?=$this->corretor->nome?>">
<input type="hidden" name="matricula" value="<?=$this->corretor->matricula?>">
<input type="submit" value="gravar">
</form>
<a href="<?=$this->url('cadastros',[
'controller' => 'corretor'    
])?>">Voltar</a>
