<?php
use Laminas\View\View;

/**
 * @var $this View
 */
?>
<tr>
<td><a href="<?=$this->url('cadastros',[
    'controller' => 'corretor',
    'action'    => 'editar',
    'matricula' => $this->matricula
])?>"><?=$this->matricula?></a></td>
<td><?=$this->nome?></td>
<td><a href="<?=$this->url('cadastros',[
    'controller' => 'corretor',
    'action'    => 'apagar',
    'matricula' => $this->matricula
])?>">X</a></td>
</tr>