<?php

use Laminas\View\View;

/**
 * @var $this View
 */
?>
<tr>
    <td><a href="<?= $this->url('cadastros', [
                        'controller' => 'imovel',
                        'action'    => 'editar',
                        'matricula' => $this->matricula
                    ]) ?>"><?= $this->matricula ?></a></td>
    <td><?= $this->nome ?></td>
    <td><a href="<?= $this->url('cadastros', [
                        'controller' => 'imovel',
                        'action'    => 'apagar',
                        'matricula' => $this->matricula
                    ]) ?>">X</a></td>
</tr>