<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<div class="jumbotron">
    <h1 class="display-4">Acesso ao Sistema</h1>

    <p>
        <form action="<?=$this->url('application',[
            'action' => 'login'
        ])?>" method="post">
        Usuário: <input type="text" name="usuario" autofocus="autofocus"/><br/>
        Senha: <input type="password" name="senha"/><br/>
        <input type="submit" value="entrar"/>
        </form>
    </p>
</div>
