<?php

/**
 * @var $this Laminas\View\Renderer\PhpRenderer
 */
?>
<form action="">
    <h1>Cadastros</h1>
    <ul>
        <li><a href="<?= $this->url('cadastros', [
                            'controller' => 'corretor'
                        ]) ?>">Cadastro de Corretores</a></li>

        <li><a href="<?= $this->url('cadastros', [
                            'controller' => 'imovel'
                        ]) ?>">Cadastro de Imóveis</a></li>
    </ul>
    <p>
        <a href="<?= $this->url('application', [
                        'controller' => 'index',
                        'action' => 'logout'
                    ]) ?>">Sair</a>
    </p>
</form>